#if   defined(ARDUINO_AVR_ADK)       
    #define AVR
#elif defined(ARDUINO_AVR_BT)
    #define AVR
#elif defined(ARDUINO_AVR_DUEMILANOVE)       
    #define AVR
#elif defined(ARDUINO_AVR_ESPLORA)       
    #define AVR
#elif defined(ARDUINO_AVR_ETHERNET)       
    #define AVR
#elif defined(ARDUINO_AVR_FIO)       
    #define AVR
#elif defined(ARDUINO_AVR_GEMMA)
    #define AVR
#elif defined(ARDUINO_AVR_LEONARDO)       
    #define AVR
#elif defined(ARDUINO_AVR_LILYPAD)
    #define AVR
#elif defined(ARDUINO_AVR_LILYPAD_USB)
    #define AVR
#elif defined(ARDUINO_AVR_MEGA)       
    #define AVR
#elif defined(ARDUINO_AVR_MEGA2560)       
    #define AVR
#elif defined(ARDUINO_AVR_MICRO)       
    #define AVR
#elif defined(ARDUINO_AVR_MINI)       
    #define AVR
#elif defined(ARDUINO_AVR_NANO)       
    #define AVR
#elif defined(ARDUINO_AVR_NG)       
    #define AVR
#elif defined(ARDUINO_AVR_PRO)       
    #define AVR
#elif defined(ARDUINO_AVR_ROBOT_CONTROL)       
    #define AVR
#elif defined(ARDUINO_AVR_ROBOT_MOTOR)       
    #define AVR
#elif defined(ARDUINO_AVR_UNO)       
    #define AVR
#elif defined(ARDUINO_AVR_YUN)       
    #define AVR
#endif

